apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: service-mesh-playground
  labels:
    app: order-service
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
      version: v1
  template:
    metadata:
      labels:
        app: order-service
        version: v1
    spec:
      containers:
      - name: order-service
        image: service-mesh-playground/order-service:latest
        ports:
        - containerPort: 3003
        env:
        - name: SERVICE_VERSION
          value: "v1"
        - name: PAYMENT_SERVICE_URL
          value: "http://payment-service:3004"
        - name: NOTIFICATION_SERVICE_URL
          value: "http://notification-service:3005"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3003
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3003
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: service-mesh-playground
  labels:
    app: order-service
spec:
  selector:
    app: order-service
  ports:
  - port: 3003
    targetPort: 3003
    protocol: TCP
  type: ClusterIP
