apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: service-mesh-playground
  labels:
    app: payment-service
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service
      version: v1
  template:
    metadata:
      labels:
        app: payment-service
        version: v1
    spec:
      containers:
      - name: payment-service
        image: service-mesh-playground/payment-service:latest
        ports:
        - containerPort: 3004
        env:
        - name: SERVICE_VERSION
          value: "v1"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3004
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3004
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: service-mesh-playground
  labels:
    app: payment-service
spec:
  selector:
    app: payment-service
  ports:
  - port: 3004
    targetPort: 3004
    protocol: TCP
  type: ClusterIP
